image: hugomods/latest

variables:
  HUGO_ENV: production
  THEME_URL: "github.com/gdr-sdl/theme"

default:
  before_script:
    - hugo version
    - hugo mod get -u $THEME_URL
    - apt update
    - apt install hugo
    # - hugo version

# Use everywhere except on the default branch
test:
  script:
    - hugo
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

# Run only on the default branch
create-pages:
  stage: deploy
  script:
    - hugo --config hugo.toml
  pages: true
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
