baseURL = "https://gdr-scilog.cnrs.fr/"
languageCode = 'fr-fr'
title = 'GdR SciLog'
theme = "mon-theme"
canonifyURLs = true
enableRobotsTXT = true
copyright = "&copy; {currentYear} All right reserved contact@scilog.fr"
enableEmoji = true

[taxonomies]
  archive = "archives"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

